env: traffic_junction

env_args:
  entity_scheme: True
  difficulty: easy
  vision: 1
  seed:
  

test_nepisode: 160
test_interval: 50000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 4000000  
